// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {time} from '../models';
import {app} from '../models';

export function AddHost(arg1:string,arg2:string,arg3:number,arg4:string):Promise<main.HostCfgJSON>;

export function Attach(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ClientOp(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ClientOpAll(arg1:string,arg2:string):Promise<Record<string, string>>;

export function DetectDaemon():Promise<Record<string, any>>;

export function FmtAgo(arg1:time.Time):Promise<string>;

export function FmtBytes(arg1:number):Promise<string>;

export function FmtCredit(arg1:number):Promise<string>;

export function FmtDuration(arg1:number):Promise<string>;

export function FmtTime(arg1:time.Time):Promise<string>;

export function GetAllSnapshots():Promise<Record<string, app.Snapshot>>;

export function GetDaemonStatus():Promise<string>;

export function GetDiskUsage(arg1:string):Promise<app.DiskInfo>;

export function GetHistory(arg1:string):Promise<Array<app.HistPoint>>;

export function GetHosts():Promise<Array<main.HostCfgJSON>>;

export function GetPrefs(arg1:string):Promise<Record<string, string>>;

export function GetSnapshot(arg1:string):Promise<app.Snapshot>;

export function GetStats(arg1:string):Promise<Array<app.StatSeries>>;

export function GetXferHistory(arg1:string):Promise<Array<app.XferPoint>>;

export function GetVersion():Promise<Record<string, string>>;

export function LookupAccount(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ProjColor(arg1:string):Promise<string>;

export function ProjectOp(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RemoveHost(arg1:string):Promise<void>;

export function RefreshAll():Promise<number>;

export function SetPrefs(arg1:string,arg2:Array<any>):Promise<void>;

export function StartDaemon():Promise<void>;

export function StopDaemon():Promise<void>;

export function TaskOp(arg1:string,arg2:string,arg3:string):Promise<void>;

export function TestHost(arg1:string,arg2:number,arg3:string):Promise<string>;

export function TransferOp(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateHost(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string):Promise<main.HostCfgJSON>;
